# Generated by Django 5.2.7 on 2025-10-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_key', models.IntegerField(unique=True)),
                ('meeting_name', models.CharField(max_length=200)),
                ('meeting_official_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('circuit_image', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('circuit_key', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_colour', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('livrea', models.URLField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.IntegerField(unique=True)),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_type', models.CharField(max_length=50)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('circuit_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.race')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('broadcast_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('circuit_image', models.URLField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gp_count', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('driver_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('openf1_id', models.CharField(blank=True, max_length=50, null=True)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('gap_to_leader', models.CharField(blank=True, max_length=50, null=True)),
                ('q1', models.CharField(blank=True, max_length=50, null=True)),
                ('q2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3', models.CharField(blank=True, max_length=50, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'driver'], name='api_result_session_4382b0_idx'), models.Index(fields=['session', 'position'], name='api_result_session_f482ef_idx'), models.Index(fields=['driver', 'position'], name='api_result_driver__72b624_idx')],
            },
        ),
    ]
