# Generated by Django 5.2.7 on 2025-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name_acronym', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('number', models.IntegerField(unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('team_color', models.CharField(max_length=50)),
            ],
        ),
    ]
