# Generated by Django 5.2.7 on 2025-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name_acronym',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='team',
            new_name='broadcast_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='points',
            new_name='gp_count',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='team_color',
        ),
        migrations.AddField(
            model_name='driver',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='poles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='team_colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
