# Generated by Django 5.2.7 on 2025-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
        migrations.AlterField(
            model_name='race',
            name='circuit_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
