# Generated by Django 5.2.7 on 2025-10-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_race_circuit_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='circuit_image',
            new_name='headshot_url',
        ),
    ]
