# Generated by Django 5.2.7 on 2025-10-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_acronym_driver_acronym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_colour', models.CharField(max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('livrea', models.URLField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='team_colour',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='team_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='api.team'),
        ),
    ]
