# Generated by Django 5.2.7 on 2025-10-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_remove_driver_team_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
