# Generated by Django 5.2.7 on 2025-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_circuit_image_driver_headshot_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='circuit_image',
        ),
    ]
