# Generated by Django 5.2.7 on 2025-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
