# Generated by Django 5.2.7 on 2025-10-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_team_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
