# Generated by Django 5.2.7 on 2025-10-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_driver_position_remove_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_key', models.IntegerField(unique=True)),
                ('meeting_name', models.CharField(max_length=200)),
                ('official_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('circuit_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='openf1_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.IntegerField(unique=True)),
                ('session_type', models.CharField(max_length=50)),
                ('date_start', models.DateTimeField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.race')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('q1', models.FloatField(blank=True, null=True)),
                ('q2', models.FloatField(blank=True, null=True)),
                ('q3', models.FloatField(blank=True, null=True)),
                ('gap_to_leader', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.session')),
            ],
        ),
    ]
