# Generated by Django 5.2.7 on 2025-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_duration_result_time_session_session_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='circuit_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='circuit_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
