# Generated by Django 5.2.7 on 2025-10-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_race_circuit_key_session_circuit_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='point',
            new_name='points',
        ),
    ]
