# Generated by Django 5.2.7 on 2025-10-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_point_driver_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='official_name',
        ),
        migrations.AddField(
            model_name='race',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
