# Generated by Django 5.2.7 on 2025-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_result_gap_to_leader_alter_result_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
    ]
