# Generated by Django 5.2.7 on 2025-10-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_race_circuit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_ref',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='openf1_id',
        ),
    ]
