# Generated by Django 5.2.7 on 2025-10-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_driver_driver_ref_remove_driver_openf1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='openf1_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
