# Generated by Django 5.2.7 on 2025-10-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_driver_driver_ref_driver_openf1_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_ref',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='openf1_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='session_key',
        ),
    ]
