# Generated by Django 5.2.7 on 2025-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_driver_driver_ref_remove_driver_openf1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='openf1_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_order_number',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
    ]
