# Generated by Django 5.2.7 on 2025-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_driver_driver_ref_driver_openf1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
