# Generated by Django 5.2.7 on 2025-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_race_date_start_alter_race_circuit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_order_number',
        ),
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
    ]
