# Generated by Django 5.2.7 on 2025-10-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_race_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
