# Generated by Django 5.2.7 on 2025-10-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_race_circuit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
    ]
