# Generated by Django 5.2.7 on 2025-10-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_result_api_result_session_4382b0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='circuit_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
